#!/usr/bin/env python3
"""
code/pipeline/preprocess/create_tooth_detail.py

Generate a multi-view CBCT composite image for each tooth in a case.

Layout — 3×3 grid, one plane per row, every cell the same size
──────────────────────────────────────────────────────────────

┌─────────────┬─────────────┬─────────────┐
│ AXIAL crown │  AXIAL mid  │  AXIAL root │  row 1  (Z-cuts, crown → apex)
├─────────────┼─────────────┼─────────────┤
│ CORONAL post│ CORONAL mid │ CORONAL ant │  row 2  (Y-cuts, P → A)
├─────────────┼─────────────┼─────────────┤
│  SAG right  │   SAG mid   │  SAG left   │  row 3  (X-cuts, patient R → L)
└─────────────┴─────────────┴─────────────┘

Every tile carries the target tooth outlined in red, and — on lower teeth —
the mandibular canal filled with a translucent yellow wash, the colour the 3D
renders already use for it (create_3d_renders.CANAL_COLOR). The canal is what the root-apex
panels are read against, so it is marked rather than left to be found; it is
filled rather than outlined because at these zoom levels its cross-section is
only a few pixels wide and nothing downstream asks what is inside it.

Every tile is centred on the tooth. The coronal and sagittal rows share one
window — the tooth plus the maxilla/mandible bone in its own column — at one
mm-per-pixel scale, so those two are directly comparable; that window is
CENTRED on the tooth and sized from its longer (root) side, so the bone past
the apex stays in frame and the crown gets the same clearance above it rather
than sitting on the tile border. The axial row is centred the same way but zoomed
in further (DEFAULT_AXIAL_SCALE), because an axial cut through a tooth is
about one tooth wide and the shared window is sized by the tooth's HEIGHT --
at the shared scale most of the axial tile was the opposite side of the arch.

There is no case-level context panel (panoramic / 3D render) any more: the
nine slice tiles fill the grid. The whole-arch panoramic and the 3D renders
are still generated by their own scripts and are still separate images in the
VQA set — they are simply not pasted into the tooth composite.

Output
──────
  {case_id}_tooth{FDI}_composite.png
  {case_id}_tooth_captions.json   -- {"tooth_16_composite": "<caption>", ...}

Each caption is written at generation time: a static description of the grid
(identical for every tooth now that the layout no longer varies), plus terse
fragments for any case finding in --facts-file that names that tooth. See the
Caption section below.

Usage
─────
  # Single case — all teeth
  python code/pipeline/preprocess/create_tooth_detail.py \
      --volume  dataset/validate/images/S0050_0000.nii.gz \
      --mask    dataset/validate/masks/S0050.nii.gz \
      --facts-file dataset/validate/facts/S0050.json \
      --out-dir     outputs/tooth_composite/ \
      --fdi 16

  # Specific teeth only
  python code/pipeline/preprocess/create_tooth_detail.py ... --fdi 16 46

  # Batch with limit
  python code/pipeline/preprocess/create_tooth_detail.py \
      --volumes-dir dataset/images/ \
      --masks-dir   dataset/predictions/ \
      --out-dir     outputs/tooth_composite/ --limit 5
"""

import os, sys, json
import numpy as np
from PIL import Image, ImageDraw

# Side determination is shared with create_panoramic.py rather than
# reimplemented, for the same reason load_as_ras lives in one place: two
# copies of "which end of X is the patient's right" are two chances to
# disagree, and a disagreement mirrors the markers on one script's images.
# The facts-parsing helpers come from there for the same reason: one
# definition of "how a facts.json field is read" across all the captions.

# Repo bootstrap. Finds code/ by walking up for _repo.py, so this file does not
# care how deep it sits, and puts every code group on sys.path so the flat
# `import postprocess_pred` works across groups. See code/_repo.py.
import sys as _sys
import pathlib as _pathlib
_sys.path.insert(0, str(next(
    p for p in _pathlib.Path(__file__).resolve().parents
    if (p / "_repo.py").is_file())))
from _repo import REPO_ROOT, add_code_paths  # noqa: E402
add_code_paths()

from create_panoramic import (RIGHT_FDI, LEFT_FDI, _side_anchor,
                              load_case_facts, _normalize_fdi_list,
                              _normalize_bridge_spans)
# The maxilla-coverage verdict and its threshold live in create_3d_renders and
# are imported, never restated: the composites that get skipped here, the
# captions written there, and audit_facts.py must all agree on what "the
# maxilla is not in this volume" means, or a case ends up with no upper
# composites and a caption still promising them.
from create_3d_renders import (MIN_ARCH_BONE_MM3, arch_coverage,
                               mask_label_volumes,
                               CANAL_IDS, CANAL_COLOR, CANAL_COLOR_NAME)

# The mandibular canal is drawn on these composites in the SAME yellow, and
# called by the SAME colour word, as on the 3D renders -- both imported above,
# never restated. A reader (or the VLM) who learns "yellow is the mandibular
# canal" from one image must not meet a different colour on the other.
_CANAL_IDS_ARR = np.array(sorted(CANAL_IDS))

# How opaque that yellow patch is. Not 1.0: the canal is drawn filled so it can
# be found at a glance, but an opaque patch also asserts its segmented border
# as fact. At 0.7 the underlying grey -- the lumen and, where the segmentation
# strays, whatever it has actually covered -- still shows through, so the patch
# reads as a marker over the anatomy rather than as a replacement for it, while
# staying unmistakably yellow against bone.
CANAL_ALPHA = 0.7

# FDI codes this script treats as maxillary. Permanent only -- these index
# tooth composites, and the mask's label map is FDI for 11-48 alone (see the
# note in audit_facts.py about labels 50+ being other anatomy).
MAXILLA_FDIS = frozenset(range(11, 19)) | frozenset(range(21, 29))


# ── Text ──────────────────────────────────────────────────────────────────────
#
# PIL's built-in bitmap font is ~11 px tall and cannot be scaled on older
# Pillow builds, which is why every label on this composite used to be
# unreadable next to a 1344-px canvas. A real TrueType face is loaded instead
# so label sizes can scale with the canvas; the bitmap font stays as a
# last-resort fallback so a machine without DejaVu still renders something.

_FONT_PATHS = {
    False: ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",),
    True:  ("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",),
}
_FONT_CACHE = {}


def _font(size, bold=False):
    """A scalable font at `size` px, cached; bitmap default if none is found."""
    key = (int(size), bool(bold))
    if key in _FONT_CACHE:
        return _FONT_CACHE[key]
    from PIL import ImageFont
    font = None
    for path in _FONT_PATHS[bool(bold)] + _FONT_PATHS[False]:
        try:
            font = ImageFont.truetype(path, int(size))
            break
        except OSError:
            continue
    if font is None:
        try:               font = ImageFont.load_default(size=int(size))
        except TypeError:  font = ImageFont.load_default()
    _FONT_CACHE[key] = font
    return font


def _text_size(draw, text, font):
    """(w, h) of `text` in `font`, measured rather than guessed at 7 px/char."""
    x0, y0, x1, y1 = draw.textbbox((0, 0), text, font=font)
    return x1 - x0, y1 - y0


def _vlabel(canvas, box, text, font, color=(235, 235, 235)):
    """
    Paste `text` rotated 90° CCW (reading bottom-to-top), centred in `box`.

    Drawn on its own horizontal strip and rotated, because PIL cannot draw
    rotated text directly. The strip is the box with its axes swapped, so the
    rotation lands exactly on the box with no resampling of the glyphs.
    """
    x, y, w, h = box
    strip = Image.new("RGB", (max(1, h), max(1, w)), (0, 0, 0))
    d     = ImageDraw.Draw(strip)
    x0, y0, x1, y1 = d.textbbox((0, 0), text, font=font)
    d.text(((h - (x1 - x0)) // 2 - x0, (w - (y1 - y0)) // 2 - y0),
           text, fill=color, font=font)
    canvas.paste(strip.rotate(90, expand=True), (x, y))


# ── Windowing ─────────────────────────────────────────────────────────────────

def _window(arr, lo_pct=0.5, hi_pct=99.5):
    """Compute percentile window from arr itself (for full-slice axial)."""
    lo  = np.percentile(arr, lo_pct)
    hi  = np.percentile(arr, hi_pct)
    out = np.clip((arr - lo) / max(hi - lo, 1e-6), 0.0, 1.0)
    return (out * 255).astype(np.uint8)


def _apply_window(arr, lo_val, hi_val):
    """Apply pre-computed window bounds — never recompute on a small crop."""
    out = np.clip((arr.astype(np.float32) - lo_val) / max(hi_val - lo_val, 1e-6), 0., 1.)
    return (out * 255).astype(np.uint8)


def _resolve_window(volume, window_center, window_width, lo_pct, hi_pct):
    """
    Decide the (lo_val, hi_val) grey-level bounds for one case.

    Fixed HU window when window_center/window_width are given (the default --
    see DEFAULT_WINDOW_CENTER); percentiles of this volume when they are not.
    Percentile mode is kept only as an escape hatch for volumes that are not
    HU-calibrated, where a fixed window means nothing; it is the mode that
    made brightness drift between cases and clipped enamel to white.
    """
    if window_center is not None and window_width is not None:
        return (float(window_center) - float(window_width) / 2.0,
                float(window_center) + float(window_width) / 2.0)
    return (float(np.percentile(volume, lo_pct)),
            float(np.percentile(volume, hi_pct)))


def _crop2d(arr, r0, r1, c0, c1, fill):
    """
    Crop arr[r0:r1+1, c0:c1+1], allowing the window to run off any edge.

    The out-of-volume part is filled with `fill` rather than the window being
    slid back inside, so a tooth near the edge of the FOV still sits in the
    centre of its own tile.
    """
    out = np.full((r1 - r0 + 1, c1 - c0 + 1), fill, dtype=arr.dtype)
    sr0, sr1 = max(r0, 0), min(r1, arr.shape[0] - 1)
    sc0, sc1 = max(c0, 0), min(c1, arr.shape[1] - 1)
    if sr0 <= sr1 and sc0 <= sc1:
        out[sr0-r0:sr1-r0+1, sc0-c0:sc1-c0+1] = arr[sr0:sr1+1, sc0:sc1+1]
    return out


def _tooth_outline_2d(tooth_2d, bridge=4, width=2):
    """
    Return an outer border mask, `width` voxels thick, for a 2D tooth slice.

    Used for the target tooth. The mandibular canal is painted solid instead
    (see _canal_region in make_tooth_composite), so this stays what it always
    was: the tooth's border, keeping its interior visible.

    Multi-root molars appear as separate blobs at the root level. We bridge
    the gap between roots with morphological closing (dilation → erosion),
    fill any interior holes, then extract the outer boundary.

    The border is thickened INWARD (erode further, subtract) rather than by
    dilating outward, so a thicker line never grows the tooth's apparent
    silhouette -- the outline still traces the segmentation boundary exactly,
    it just paints more pixels of the tooth's own edge. Growing outward would
    creep over the neighbouring tooth's enamel on a tight contact.

    Parameters
    ----------
    tooth_2d : (H, W) bool  — tooth voxels in one 2D slice
    bridge   : closing radius in voxels (default 4 — bridges root gaps)
    width    : border thickness in voxels (1 = the old hairline)
    """
    from scipy.ndimage import binary_erosion, binary_dilation, binary_fill_holes
    if not tooth_2d.any():
        return np.zeros_like(tooth_2d, dtype=bool)
    # Closing = dilate then erode: bridges small gaps without expanding the shape much
    merged = binary_erosion(binary_dilation(tooth_2d, iterations=bridge),
                            iterations=bridge)
    # Fill enclosed holes (e.g. pulp cavity gaps)
    filled = binary_fill_holes(merged)
    inner = binary_erosion(filled, iterations=max(1, int(width)))
    if not inner.any():          # tiny structure -- keep the hairline rather
        inner = binary_erosion(filled)   # than painting the whole thing solid
    return filled & ~inner


# ── Label IDs — mask label == FDI number ─────────────────────────────────────
#  0          background
#  1          Lower Jawbone      2   Upper Jawbone
#  3          Left IAC           4    Right IAC
#  5          Left Max Sinus     6    Right Max Sinus
#  7          Pharynx
#  8          Bridge             9   Crown          10  Implant
#
#  Tooth labels equal FDI numbers:
#  11–18      Upper RIGHT teeth  (FDI 11–18)   gap: 19–20 unused
#  21–28      Upper LEFT  teeth  (FDI 21–28)   gap: 29–30 unused
#  31–38      Lower LEFT  teeth  (FDI 31–38)   gap: 39–40 unused
#  41–48      Lower RIGHT teeth  (FDI 41–48)
#
#  52         Right Mandibular Incisive Canal
#  51         Left  Mandibular Incisive Canal
#  45         Lingual Canal

# Seg labels are non-contiguous (gaps at 19-20, 29-30, 39-40)
_UPPER_TIDS = list(range(11, 19)) + list(range(21, 29))   # upper left (11-18) + upper right (21-28)
_LOWER_TIDS = list(range(31, 39)) + list(range(41, 49))   # lower right (31-38) + lower left (41-48)
_TEETH_IDS  = _UPPER_TIDS + _LOWER_TIDS

# Panel tags, one per column of each row. Written out in full rather than
# abbreviated (P/M/A) so the tag says what the cut is without the caption
# having to decode it. Used by make_tooth_composite AND quoted in the caption
# text below -- kept in one place so the two can't drift apart.
#
# Every tag names a PATIENT direction (or, in the axial row, a part of the
# tooth) -- never a tooth SURFACE. One constant serves all 32 teeth, and no
# surface name is true for all 32 along a fixed anatomical axis:
#
#   sagittal cuts step along X, the medio-lateral axis. For a POSTERIOR tooth
#   that axis is buccal-lingual; for an ANTERIOR tooth it is mesial-distal,
#   because an incisor's labial surface faces anteriorly (+Y), not laterally.
#   So the old "sagittal buccal ... sagittal lingual" was right for molars and
#   premolars and simply wrong for incisors and canines, where those panels
#   are mesial and distal cuts.
#
# Right -> left is what X actually is, for every tooth, and it matches the
# drawn markers ("L" = the patient's left). Which surface that lands on for
# THIS tooth follows from its quadrant, so the caption says it in words --
# see _TOOTH_SAGITTAL_TEXT.
_AXIAL_TAGS    = ("axial crown", "axial mid", "axial root")
_CORONAL_TAGS  = ("coronal posterior", "coronal mid", "coronal anterior")
_SAGITTAL_TAGS = ("sagittal right", "sagittal mid", "sagittal left")


def detect_right_low_x(mask):
    """
    Is the PATIENT'S RIGHT at low X in this (already RAS+) mask?

    Read from the segmentation, never assumed. On this dataset the answer is
    True — right-quadrant teeth (11-18, 41-48) sit at low X while left ones
    sit at high X — which is the OPPOSITE of what the volume's RAS+ affine
    implies (+X = patient right). A hard-coded convention therefore mirrors
    every B/L and L/R marker, and would do so silently.

    Uses create_panoramic's `_side_anchor`, so both scripts decide laterality
    the same way. Returns None when neither side can be anchored, leaving the
    caller to decide (markers are then drawn on the dataset's usual
    convention rather than omitted, since a tooth composite always has a
    quadrant to speak of).
    """
    r = _side_anchor(mask, RIGHT_FDI, 'right')
    l = _side_anchor(mask, LEFT_FDI,  'left')
    if r is None or l is None:
        return None
    return float(r[0]) < float(l[0])


def _tooth_extent(mask, tooth_tid):
    """
    (lo, hi, n_voxels) bounding box of the tooth's LARGEST connected blob.

    Masks sometimes carry a stray second blob under the same FDI label —
    A014's 38 has a 20k-voxel fragment (6% of the label) about 10 mm above
    the crown. Taken literally it doubles the tooth's Z extent, and since
    the row-2 crop and through it the whole composite's row height are
    derived from that extent, one mislabelled blob reshapes the entire
    image. Labelling is done on the tooth's own bounding box, not the full
    volume, so this stays cheap.
    """
    from scipy.ndimage import label as _label

    vox = np.argwhere(mask == tooth_tid)
    if len(vox) < 5:
        return None, None, 0
    lo, hi = vox.min(axis=0), vox.max(axis=0)
    sub    = (mask[lo[0]:hi[0]+1, lo[1]:hi[1]+1, lo[2]:hi[2]+1] == tooth_tid)
    lab, n = _label(sub)
    if n > 1:
        sizes    = np.bincount(lab.ravel())
        sizes[0] = 0
        sub_vox  = np.argwhere(lab == int(sizes.argmax()))
        lo, hi   = lo + sub_vox.min(axis=0), lo + sub_vox.max(axis=0)
    return lo, hi, len(vox)


# ── Composite image ───────────────────────────────────────────────────────────

# Default zoom of the shared crop window. Defined ONCE: it used to be written
# out separately in make_tooth_composite's signature, process_case's signature
# and the --window-scale CLI default, so changing the function default alone
# changed nothing -- every real render goes through the CLI/process_case path,
# which passed its own copy straight over the top.
DEFAULT_WINDOW_SCALE = 1.25

# The axial row's window, as a fraction of the shared one. The shared window's
# size is set by the tooth's HEIGHT plus the bone above/below its apex, which
# is the right amount of anatomy for the coronal and sagittal rows -- and far
# more than the axial row needs, since an axial cut through a premolar is
# about one tooth wide. At 1.0 the axial tile spent most of its area on the
# opposite side of the arch and the palate. This zooms that row in on the
# tooth's own quadrant.
#
# NOTE: this is the one place the nine tiles stop sharing a mm-per-pixel
# scale. Within a row it still holds, and the coronal and sagittal rows --
# the two that show the same vertical anatomy and get compared against each
# other -- are still identical. The captions say the axial row is zoomed.
#
# Lowered from 0.55 when the shared window stopped being anchored at the crown
# and became centred on the tooth: that change makes nat_h about 1.25x taller,
# and the axial window is a fraction OF nat_h, so keeping 0.55 would have
# zoomed the axial row out along with it. This keeps that row framed as it was.
DEFAULT_AXIAL_SCALE = 0.45


# ── Default intensity window (grey-level mapping), in HU ──────────────────────
#
# NOT to be confused with DEFAULT_WINDOW_SCALE above, which is a *crop* window
# (how much anatomy is in frame). This pair is the radiological window --
# which intensities map to black and to white.
#
# This used to be a percentile window (lo_pct=0.5, hi_pct=99.5) taken from
# each case's own volume, which was wrong twice over:
#
#   1. Brightness drifted case to case. The 99.5th percentile is a property
#      of the FOV, not of the tissue: a scan with more air in frame pushes it
#      down. Measured over the validate split it ranges 1423 (A018) to 4332
#      (A034) -- a 3x spread in the white point, so identical enamel came out
#      a different grey in every case.
#   2. Enamel and dental material were both pure white. Tooth voxels alone
#      reach p95 ~= 2800-4200, i.e. ABOVE the percentile white point on most
#      cases, so enamel was already saturated before a restoration -- which
#      runs 5000 to >30000 -- could be told apart from it.
#
# A fixed window fixes both. These volumes are HU-calibrated (air ~= -1000,
# soft tissue ~= -200..0), so the same numbers mean the same tissue in every
# case. The bounds are chosen to span exactly air -> just past enamel:
#
#      -1000  air                            ->   0    black
#       -100  soft tissue                    ->  52
#       1200  dentin                         -> 128    mid grey
#       1500  cortical bone                  -> 145
#       2800  enamel                         -> 220    bright, NOT clipped
#      >3400  amalgam / crown / implant      -> 255    the only pure white
#
# Enamel landing at ~220 rather than 255 is the whole point: it leaves the
# top of the range free for dental material, which is what makes the two
# separable by eye. Widening further would separate them more but flattens
# the bone/dentin contrast that the rest of the composite is read for.
DEFAULT_WINDOW_CENTER = 1200.0
DEFAULT_WINDOW_WIDTH  = 4400.0


def make_tooth_composite(
    volume,
    mask,
    tooth_tid,
    fdi          = None,
    right_low_x  = True,    # is the patient's RIGHT at low X? (see detect_right_low_x)
    spacing_mm   = 0.3,
    n_slices     = 3,       # slices per row (one row per plane)
    pad_frac     = 0.30,    # crop padding, as a fraction of tooth size
    bone_reach_frac= 0.50,  # how far past the apex the window follows the bone
    window_scale = DEFAULT_WINDOW_SCALE,   # overall zoom of the window (1.0 = tight)
    axial_scale  = DEFAULT_AXIAL_SCALE,    # axial row's window, relative to that
    crown_margin_frac = 0.20,  # minimum clearance past the crown tip, as a
                               # fraction of tooth height (the centred window
                               # normally gives more than this)
    tile_aspect  = 1.00,    # target W:H for EVERY tile (the grid is uniform)
    out_w        = 1120,
    window_center= DEFAULT_WINDOW_CENTER,  # grey-level window, in HU. Set BOTH
    window_width = DEFAULT_WINDOW_WIDTH,   # to None to fall back to percentiles
    lo_pct       = 0.5,                    # only used when the HU window is None
    hi_pct       = 99.5,
    box_color    = (220, 40, 40),
    canal_color  = CANAL_COLOR,   # mandibular canal overlay — yellow, as in 3D
    canal_alpha  = CANAL_ALPHA,   # ...blended, not opaque (see CANAL_ALPHA)
    outline_width= 2,       # tooth-outline thickness, in voxels
):
    """
    3×3 grid, one plane per row, aspect ratio always preserved. Every cell is
    the same size and every tile is cut at the SAME mm-per-pixel scale, from
    one window centred on the tooth:

        row 1  n_slices constant-Z cuts  (axial,    crown → apex)
        row 2  n_slices constant-Y cuts  (coronal,  posterior → anterior)
        row 3  n_slices constant-X cuts  (sagittal, patient's right → left)

    All nine are cropped the same way — the window is the tooth plus the
    maxilla/mandible bone in its own column (padded by pad_frac of the tooth's
    size, reaching bone_reach_frac past the apex, zoomed by window_scale),
    which is how the coronal and sagittal tiles were already cut. The axial
    row now follows it too, instead of being an arch-wide overview slice.

    No case-level context panel (panoramic / 3D render) is placed here any
    more: nine slice tiles fill the grid.

    Z convention (RAS+):
      Upper arch  — roots are at high Z, crowns at low Z
      Lower arch  — roots are at low  Z, crowns at high Z
    """
    t_lo, t_hi, n_vox = _tooth_extent(mask, tooth_tid)
    if n_vox < 5:
        return None

    tx0, ty0, tz0 = t_lo
    tx1, ty1, tz1 = t_hi

    upper = tooth_tid in _UPPER_TIDS

    # ── Global window: one grey-level mapping for all nine tiles ──────────────
    # Never recompute on a small crop — percentiles on 50×120 voxels are
    # statistically unstable and produce different contrast per tile. With the
    # default fixed HU window this is constant across cases too, not just
    # across tiles, which is what makes two composites comparable by eye.
    lo_val, hi_val = _resolve_window(volume, window_center, window_width,
                                     lo_pct, hi_pct)

    # ── Crop window: target tooth + its jawbone + pad_frac of tooth size ──
    # The coronal/sagittal crop is the bounding box of the TOOTH together
    # with the maxilla (upper) or mandible (lower) bone in the tooth's own
    # column, padded by pad_frac of the tooth's size on each axis.
    #
    # Anchoring to the bone instead of a fixed multiple of the tooth's own
    # height is what guarantees the root-to-bone relationship is actually in
    # frame: alveolar crest, apex, and what lies beyond it (sinus floor
    # above, inferior border / mandibular canal below) all sit inside the
    # bone label regardless of how long this particular tooth is.
    #
    # The bone label has to be restricted to the tooth's own column first --
    # taken whole it spans the entire jaw, which would blow the crop up to
    # the full FOV and shrink the tooth to a few pixels.
    jaw_id = 2 if upper else 1
    padx = max(2, round((tx1 - tx0) * pad_frac))
    pady = max(2, round((ty1 - ty0) * pad_frac))
    padz = max(2, round((tz1 - tz0) * pad_frac))

    def _centred(centre, width):
        """[lo, hi] of `width` voxels centred on `centre`.

        Deliberately NOT clipped to the volume: a window that runs off the
        edge is padded with background at crop time instead. Clipping would
        slide the window back inside, which is what pushed the tooth up
        against the top of the tile whenever the maxilla reached the top of
        the FOV — the tooth has to stay in the middle of its own view.
        """
        lo = int(centre) - width // 2
        return lo, lo + width - 1

    # X window (coronal tile width) — tooth-driven.
    x_lo = max(0,               tx0 - padx);  x_hi = min(mask.shape[0]-1, tx1 + padx)
    y_lo = max(0,               ty0 - pady);  y_hi = min(mask.shape[1]-1, ty1 + pady)

    # Z window (shared by every row-2 tile): tooth, extended to the bone on
    # the ROOT side only. Past the crown there is nothing to show, and the
    # bone label keeps going regardless — for a lower third molar it climbs
    # the ramus far above the occlusal plane, which made the crop (and with
    # it the shared row height) about 3× the tooth's own height and left the
    # whole composite mostly empty. Extending only toward the apex keeps the
    # alveolar bone, apex and inferior border / sinus floor in frame without
    # that runaway.
    # How deep into the bone the window reaches is also capped, at
    # bone_reach_frac of the tooth's own height. A maxilla is thin, so an
    # upper tooth's window stops at the sinus floor either way — but a
    # mandible is deep, and following it to the inferior border left the
    # tooth occupying a quarter of a very tall tile. Half a tooth-height of
    # bone past the apex is the usual radiographic framing and keeps the
    # tooth the subject of the tile.
    bone_col   = (mask[x_lo:x_hi+1, y_lo:y_hi+1, :] == jaw_id)
    bz         = np.where(bone_col.any(axis=(0, 1)))[0]
    bone_reach = max(padz, round((tz1 - tz0) * bone_reach_frac))
    z_lo, z_hi = int(tz0), int(tz1)
    if len(bz):
        if upper:  # upper arch: roots at high Z, crown at low Z
            z_hi = max(z_hi, min(int(bz.max()), int(tz1) + bone_reach))
        else:      # lower arch: roots at low Z, crown at high Z
            z_lo = min(z_lo, max(int(bz.min()), int(tz0) - bone_reach))
    z_lo -= padz
    z_hi += padz

    # ── Window size, then centre it on the tooth ──────────────────────────
    # Everything above only sizes the window; where it sits is decided here,
    # and it is always centred on the tooth. window_scale is THE knob for how
    # much of the jaw the tiles show — it scales the window's height, and
    # since every tile's in-plane width is that height × tile_aspect, one
    # number zooms all nine tiles together while their shapes stay put.
    # pad_frac / bone_reach_frac decide what the window contains at scale
    # 1.0; window_scale decides how far past that it goes.
    #
    # Widths come from the aspect target rather than the tooth's own width:
    # the height is set by the tooth AND the bone over/under it, so it always
    # exceeds one tooth-width, and tooth-width crops left slivers beside a
    # bone-tall tile. Growing to the target aspect brings in the neighbouring
    # teeth and the bone either side — the context these views are read
    # against.
    #
    # nat_w is used for BOTH in-plane axes of every plane, so one voxel is
    # the same number of pixels in all nine tiles: the axial's X window is the
    # coronal's X window, the sagittal's Y window is the axial's... except the
    # axial's own vertical axis (Y) is nat_h tall, matching the Z height the
    # other two rows use. Same window, same scale, three planes.
    ccx, ccy, ccz = (tx0 + tx1) // 2, (ty0 + ty1) // 2, (tz0 + tz1) // 2

    # VERTICAL window (coronal + sagittal): CENTRED on the tooth, and sized
    # from its LONGER side. Anchoring the top edge just past the crown tip put
    # the tooth hard against the top of every coronal and sagittal tile: with
    # only crown_margin_frac of clearance the occlusal surface was clipped by
    # the tile border and there was nothing above it to read the crown
    # against, while the whole rest of the height went below the apex.
    #
    # The half-height is whichever side of the tooth's centre needs more --
    # in practice the root side, which carries the bone_reach past the apex --
    # so everything that side used to show is still in frame, and the SAME
    # amount of room now appears past the crown. That is what puts the tooth
    # in the middle of the tile, and it is also what makes the window bigger:
    # the growth is entirely on the crown side.
    #
    # The cost is the opposing arch coming back into the top (upper: bottom)
    # of the tile, which the old crown anchor existed to exclude. That is
    # accepted deliberately -- a crown clipped by the tile edge is the worse
    # of the two, and the tooth's own outline marks the subject in every tile.
    #
    # The window is then TRIMMED, symmetrically so it stays centred, to what
    # the volume actually contains. Without that the window runs off the FOV
    # on cases like A008 tooth 43 (a long-rooted lower canine in a shallow
    # mandible), and _crop2d pads the outside with lo_val, which windows to
    # pure BLACK -- a black band across the tiles. Trimming costs only zoom.
    # It stops at the tooth plus its crown margin, though: past that point
    # black padding is better than cutting into the tooth itself.
    depth = mask.shape[2]
    crown_margin = max(2, round((tz1 - tz0) * crown_margin_frac))
    z_half = max(int(ccz) - z_lo, z_hi - int(ccz),
                 (int(tz1) - int(tz0)) // 2 + crown_margin)
    nat_h = max(8, round((2 * z_half + 1) * window_scale))

    room  = min(int(ccz), depth - 1 - int(ccz))     # half-height that fits
    min_h = (int(tz1) - int(tz0) + 1) + 2 * crown_margin
    nat_h = max(8, min(nat_h, max(min_h, 2 * room + 1)))

    z_lo, z_hi = _centred(ccz, nat_h)

    # nat_w follows nat_h, so it has to be derived after the trim above.
    nat_w = max(4, round(nat_h * tile_aspect))

    x_lo, x_hi           = _centred(ccx, nat_w)   # horizontal axis, coronal
    sag_y_lo, sag_y_hi   = _centred(ccy, nat_w)   # horizontal axis, sagittal

    # Axial row: its own, tighter square window (see DEFAULT_AXIAL_SCALE),
    # centred on the tooth so what surrounds it is its OWN quadrant rather
    # than the whole arch.
    ax_w = max(8, round(nat_w * axial_scale))
    ax_h = max(8, round(nat_h * axial_scale))
    ax_x_lo, ax_x_hi     = _centred(ccx, ax_w)    # horizontal axis, axial
    ax_y_lo, ax_y_hi     = _centred(ccy, ax_h)    # vertical axis, axial

    # ── Enforce the viewing convention: patient's LEFT on the image's right ─
    # Every view whose horizontal axis is X (the axials and the coronals) is
    # mirrored when this volume has the patient's left at low X, so the side
    # a reader finds on the right is the same in every composite regardless
    # of the source volume's own orientation. Nothing downstream has to know
    # which way the scan was stored: after this flip the "L" always belongs
    # on the right, and buccal is always the tooth's own quadrant side.
    flip_lr = not right_low_x

    # ── Slice positions — one row per plane, n_slices cuts through the tooth ─
    # Each row steps through the tooth's own extent at (i+1)/(n+1), i.e. the
    # crop window is fixed but the cut plane moves, so the three tiles in a
    # row are the same view at different depths.
    def _positions(lo, hi, reverse=False):
        pos = [int(lo + (i + 1) / (n_slices + 1) * (hi - lo)) for i in range(n_slices)]
        return pos[::-1] if reverse else pos

    # Axial row reads crown → apex. In RAS+ an upper crown is at LOW Z and an
    # upper root at high Z; the lower arch is the other way round, so the
    # lower arch's positions are reversed to keep both rows in the same
    # anatomical order.
    z_positions = _positions(tz0, tz1, reverse=not upper)
    # Coronal row reads posterior → anterior (+Y is anterior in RAS+).
    y_positions = _positions(ty0, ty1)
    # Sagittal row reads the patient's RIGHT → LEFT, so the row steps the same
    # way the images are laid out (the flip puts the patient's left on the
    # image's right) and the same way the "L" marker points. It used to read
    # buccal → lingual, which reversed with the quadrant and, for an anterior
    # tooth, named the wrong pair of surfaces entirely -- see _SAGITTAL_TAGS.
    # Only this volume's laterality decides the direction now.
    x_positions    = _positions(tx0, tx1, reverse=not right_low_x)

    def _overlay_outline(img, outline_xy, col_flip=False, color=box_color,
                         alpha=1.0):
        """Paint a boolean overlay (outline or solid region) in `color`,
        matching the view transform.
        col_flip=False → [::-1,:]  (axial/coronal: 180°+flip)
        col_flip=True  → [::-1,::-1] (sagittal: 180° only)

        `alpha` < 1 blends with the grey underneath instead of replacing it,
        which is how the canal's filled patch keeps the anatomy under it
        visible. The tooth outline is opaque (alpha=1): it is a boundary line,
        and a blended one on bright enamel washes out to near-white.
        """
        if outline_xy.any():
            arr = np.array(img)
            sel = outline_xy.T[::-1, ::-1] if col_flip else outline_xy.T[::-1, :]
            if alpha >= 1.0:
                arr[sel] = color
            else:
                arr[sel] = np.round(alpha * np.asarray(color, dtype=np.float32)
                                    + (1.0 - alpha) * arr[sel]).astype(np.uint8)
            return Image.fromarray(arr)
        return img

    # ── Mandibular canal overlay ──────────────────────────────────────────
    # Drawn on LOWER composites only, in the same yellow the 3D renders use.
    # The canal is a mandibular structure, so on an upper tooth it is simply
    # not in the window -- and gating here rather than relying on that keeps
    # the image and build_tooth_static_caption's yellow sentence, which is
    # gated the same way, from ever disagreeing.
    #
    # It is FILLED, not outlined like the tooth. The canal is a few
    # millimetres across, so at these zoom levels its cross-section is a
    # handful of pixels: a 2-px ring around it read as a smudge, and what is
    # inside a canal lumen is not something anything downstream asks about.
    # What IS asked -- where the canal runs and how far it sits from the root
    # apices -- is exactly what a filled patch shows most plainly. The tooth
    # keeps its outline for the opposite reason: its interior (canal space,
    # restorations, caries) is the whole subject of the read.
    #
    # The fill is blended at CANAL_ALPHA rather than laid on opaque, so the
    # grey under it stays legible -- see the note there.
    show_canal = tooth_tid in _LOWER_TIDS

    def _canal_region(slice_2d, r0, r1, c0, c1):
        """The canal's own voxels in one cropped 2D slice, solid."""
        if not show_canal:
            return np.zeros((r1 - r0 + 1, c1 - c0 + 1), dtype=bool)
        return _crop2d(np.isin(slice_2d, _CANAL_IDS_ARR), r0, r1, c0, c1, False)

    # Canal first, tooth second, in every plane: where the two segmentations
    # touch -- exactly the case these panels exist to judge -- the red tooth
    # outline stays on top, so the target tooth is never the one painted over.
    def z_cut(z_pos):
        """Axial: X across, Y up (anterior at top), cropped like the rest."""
        zp   = int(np.clip(z_pos, 0, mask.shape[2]-1))
        crop = _crop2d(volume[:, :, zp], ax_x_lo, ax_x_hi, ax_y_lo, ax_y_hi,
                       lo_val).astype(np.float32)
        img  = Image.fromarray(_apply_window(crop, lo_val, hi_val).T[::-1, :]).convert("RGB")
        img = _overlay_outline(img, _canal_region(mask[:, :, zp], ax_x_lo,
                                                  ax_x_hi, ax_y_lo, ax_y_hi),
                               color=canal_color, alpha=canal_alpha)
        tooth_xy = _crop2d(mask[:, :, zp] == tooth_tid,
                           ax_x_lo, ax_x_hi, ax_y_lo, ax_y_hi, False)
        img = _overlay_outline(img, _tooth_outline_2d(tooth_xy, width=outline_width))
        return img.transpose(Image.FLIP_LEFT_RIGHT) if flip_lr else img

    def y_cut(y_pos):
        """Coronal: X across, Z up."""
        yp   = int(np.clip(y_pos, 0, mask.shape[1]-1))
        crop = _crop2d(volume[:, yp, :], x_lo, x_hi, z_lo, z_hi,
                       lo_val).astype(np.float32)
        img  = Image.fromarray(_apply_window(crop, lo_val, hi_val).T[::-1, :]).convert("RGB")
        img = _overlay_outline(img, _canal_region(mask[:, yp, :],
                                                  x_lo, x_hi, z_lo, z_hi),
                               color=canal_color, alpha=canal_alpha)
        tooth_xz = _crop2d(mask[:, yp, :] == tooth_tid,
                           x_lo, x_hi, z_lo, z_hi, False)
        img = _overlay_outline(img, _tooth_outline_2d(tooth_xz, width=outline_width))
        return img.transpose(Image.FLIP_LEFT_RIGHT) if flip_lr else img

    def x_cut(x_pos):
        """Sagittal: Y across (mesial/anterior left), Z up."""
        xp   = int(np.clip(x_pos, 0, mask.shape[0]-1))
        crop = _crop2d(volume[xp, :, :], sag_y_lo, sag_y_hi, z_lo, z_hi,
                       lo_val).astype(np.float32)
        img  = Image.fromarray(_apply_window(crop, lo_val, hi_val).T[::-1, ::-1]).convert("RGB")
        img = _overlay_outline(img, _canal_region(mask[xp, :, :], sag_y_lo,
                                                  sag_y_hi, z_lo, z_hi),
                               col_flip=True, color=canal_color,
                               alpha=canal_alpha)
        tooth_yz = _crop2d(mask[xp, :, :] == tooth_tid,
                           sag_y_lo, sag_y_hi, z_lo, z_hi, False)
        return _overlay_outline(img, _tooth_outline_2d(tooth_yz, width=outline_width), col_flip=True)

    rows = [
        ("axial",    [z_cut(z) for z in z_positions], _AXIAL_TAGS),
        ("coronal",  [y_cut(y) for y in y_positions], _CORONAL_TAGS),
        ("sagittal", [x_cut(x) for x in x_positions], _SAGITTAL_TAGS),
    ]

    # ── Tile sizing — one cell size for all nine, aspect preserved ─────────
    # The grid is uniform, so the geometry is decided by out_w alone: three
    # equal columns, and a row height that gives every cell the window's own
    # aspect (nat_w:nat_h). The canvas height follows from that rather than
    # being asked for — stretching a tile to hit a requested height is the
    # one thing this must never do.
    #
    # Two black margins are reserved out of that width/height before the grid
    # is laid out — a title band across the top and a row-name column down the
    # left — so the FDI number and the plane names sit on black rather than on
    # anatomy, and can therefore be set large enough to read. out_w remains
    # the total canvas width; the grid gets what the left margin leaves.
    title_h  = max(34, round(out_w * 0.045))
    lbl_w    = max(30, round(out_w * 0.035))
    cell_w   = max(1, (out_w - lbl_w) // n_slices)
    grid_w   = cell_w * n_slices
    canvas_w = lbl_w + grid_w
    row_h    = max(1, round(cell_w * nat_h / nat_w))
    grid_h   = row_h * len(rows)
    canvas_h = title_h + grid_h

    canvas = Image.new("RGB", (canvas_w, canvas_h), (10, 10, 10))
    draw_c = ImageDraw.Draw(canvas)

    for r, (_plane, imgs, _tags) in enumerate(rows):
        for c, img in enumerate(imgs):
            canvas.paste(img.resize((cell_w, row_h), Image.LANCZOS),
                         (lbl_w + c * cell_w, title_h + r * row_h))

    # ── Title band — 'FDI nn' across the full width of the image ───────────
    draw_c.rectangle([0, 0, canvas_w - 1, title_h - 1], fill=(0, 0, 0))
    if fdi is not None:
        tfont  = _font(max(18, round(title_h * 0.55)), bold=True)
        tw, th = _text_size(draw_c, f"FDI {fdi}", tfont)
        draw_c.text(((canvas_w - tw) // 2, (title_h - th) // 2 - 2),
                    f"FDI {fdi}", fill=(220, 220, 80), font=tfont)

    # ── Row names — vertical, in the left margin, one per row ──────────────
    rfont = _font(max(12, min(round(row_h * 0.28), round(lbl_w * 0.62))), bold=True)
    for r, (plane, _imgs, _tags) in enumerate(rows):
        _vlabel(canvas, (0, title_h + r * row_h, lbl_w, row_h),
                plane.upper(), rfont)

    # ── Dividers ──────────────────────────────────────────────────────────
    for r in range(1, len(rows)):
        y = title_h + r * row_h
        draw_c.line([(lbl_w, y), (canvas_w, y)], fill=(60, 60, 60), width=1)
    for c in range(1, n_slices):
        x = lbl_w + c * cell_w
        draw_c.line([(x, title_h), (x, canvas_h)], fill=(50, 50, 50), width=1)

    # ── Panel tags — with background box for legibility ────────────────────
    tag_font = _font(max(12, canvas_w // 70))
    for r, (plane, imgs, tags) in enumerate(rows):
        for c in range(len(imgs)):
            tag = tags[c] if len(imgs) == len(tags) else f"{plane} {c+1}"
            _lbl_box(draw_c, tag, lbl_w + c * cell_w + 5,
                     title_h + r * row_h + 5, font=tag_font)

    # ── Orientation markers — white text, no background ─────────────────────
    mfont = _font(max(16, canvas_w // 45), bold=True)

    def _wlbl(x, y, text, right=False):
        if right:
            x -= _text_size(draw_c, text, mfont)[0]
        draw_c.text((x, y), text, fill=(255, 255, 255), font=mfont)

    # One marker per ROW, at a row's outer bottom corner: every tile in a row
    # shares one crop window, so a letter at the row's edge speaks for all
    # three. A single letter per row is deliberate — it fixes the row's
    # orientation, and a second one opposite it is clutter over anatomy. The
    # flip above already fixed laterality, so these are constants from here on
    # — no orientation test needed.
    #
    # Every letter is a PATIENT direction, and one letter means one thing in
    # every row: "L" is the patient's LEFT, "P" is posterior. The coronal row
    # used to spend its "L" on LINGUAL, which put the same letter on opposite
    # edges of two adjacent rows meaning two different things — patient-left
    # in the axial row, lingual in the coronal — and made the side it sat on
    # depend on the quadrant. Buccal/lingual is derivable from laterality
    # anyway (buccal is the tooth's own side of the mouth), so the caption
    # says which edge that is for this tooth and the image stays unambiguous.
    def _row_markers(r, left_text=None, right_text=None):
        y = title_h + (r + 1) * row_h - round(mfont.size * 1.6)
        if left_text:
            _wlbl(lbl_w + 5, y, left_text)
        if right_text:
            _wlbl(canvas_w - 5, y, right_text, right=True)

    # Axial: "L" — the patient's left, which the flip put on the image's right.
    _row_markers(0, right_text="L")
    # Coronal: "L" — the patient's left too. Its horizontal axis is X, the same
    # axis as the axial row's and flipped the same way, so the letter belongs
    # on the same edge: image-right, for either quadrant.
    _row_markers(1, right_text="L")
    # Sagittal: "P" — posterior. [::-1,::-1] puts anterior on the left, so
    # posterior is the right edge, for either quadrant.
    _row_markers(2, right_text="P")

    return canvas

def _lbl_box(draw, text, x, y, color=(200, 200, 200), center=False, font=None):
    """Draw a label with a dark background rectangle for legibility.

    The box is measured from the text rather than assumed at 7 px/char, so it
    still fits once the font scales with the canvas.
    """
    font   = font or _font(13)
    tw, th = _text_size(draw, text, font)
    if center:
        x -= tw // 2
    draw.rectangle([x - 3, y - 2, x + tw + 3, y + th + 6], fill=(0, 0, 0))
    draw.text((x, y), text, fill=color, font=font)


# ── Caption ────────────────────────────────────────────────────────────────
#
# Per schema.json (v6.1), `tooth_{fdi}_composite` is the images_needed target
# for all six per-tooth facts -- tooth_{fdi}_morphology, _eruption,
# _endodontic_treatment, _periodontal_status, _restoration and _impaction.
# Those are exactly what the VLM has to read OFF this image, so none of
# them are spoken here: the caption describes the picture and carries only
# the case-level facts that are already known going in.
#
# The known facts are the same six case-level fields the panoramic caption
# draws on (teeth_present, teeth_absent, crowns, implants, bridge,
# ian_close_teeth), narrowed to this one FDI -- whichever of them mention
# this tooth become terse fragments, everything else is silently skipped,
# never padded with "none" text. teeth_present produces no fragment: a
# composite only exists because the tooth is in the mask, so "tooth 16
# present" says nothing the image doesn't. teeth_absent DOES produce one,
# since that is the informative case (the mask carries a label facts.json
# does not confirm).
#
# The static half is the same for every tooth: the 3x3 grid does not vary
# by FDI (see make_tooth_composite), so there is only one layout to describe.
#
# It describes the PICTURE and nothing else: what the panels are, which way
# they face, and what the red outline does and does not cover. Every rule and
# every reading tip lives in the prompt instead --
#   - "focus on tooth N, a neighbour's finding is never tooth N's"
#     -> run_vqa_inference.TOOTH_USER_TEMPLATE
#   - "bright can be enamel or material, dark can be canal or defect"
#     -> run_vqa_inference.HOW_TO_READ_A_TOOTH, and the compact
#        inference_freetext_renders.TOOTH_READING for the no-schema arm,
#        which sends no prompt block of its own.
# Both used to be stated here as well, which put two wordings of one rule a
# few hundred tokens apart and left the caption arguing with the prompt.

TOOTH_STATIC_CAPTION_INTRO = (
    "CBCT detail view of tooth FDI {fdi}: a 3x3 grid of grayscale panels, "
    "one plane per row, all centred on the tooth. 'FDI {fdi}' is printed in "
    "yellow on a black title bar at the top; each row's plane name "
    "('AXIAL', 'CORONAL', 'SAGITTAL') runs vertically down its left margin; "
    "each panel is tagged in its top-left corner. The middle and bottom rows "
    "share one scale; the top (axial) row is zoomed in further, so distances "
    "there are not comparable. "
    "Tooth {fdi} -- and only tooth {fdi} -- is outlined in red in every "
    "panel. The outline is an automatic segmentation of TOOTH SUBSTANCE: it "
    "says which tooth is the target, not exactly where its border runs (it "
    "can be slightly off), and it may exclude artificial things, like a crown."
)

# Lower composites only -- the canal is drawn only there (see show_canal in
# make_tooth_composite), and both are gated on _LOWER_TIDS so the sentence
# cannot outlive the overlay. Phrased so it stays true panel by panel: the
# canal is in the crop window of some cuts and not others, and "no yellow
# here" must not read as "this case has no canal on this side".
TOOTH_CANAL_CAPTION = (
    "The mandibular canal is filled with a translucent {colour} wash wherever "
    "it crosses a panel -- the same {colour} it is drawn in on this case's 3D "
    "renders -- so its distance to the root apices of tooth {fdi} can be read "
    "off the image directly. The patch marks WHERE the canal runs, and the "
    "grey it is laid over still shows faintly through it. A panel with no "
    "{colour} patch is a cut the canal does not pass through; it does not mean "
    "the case has no canal on this side. The only other {colour} on the image "
    "is the 'FDI {fdi}' title text, which sits on the black bar above the "
    "panels rather than on anatomy."
)

# Row-by-row descriptions. Each quotes its row's panel tags from the
# _*_TAGS tuples the renderer draws, so caption and image can't disagree.
_TOOTH_AXIAL_TEXT = (
    "axial cuts tagged {tags} -- anterior is up, white 'L' at the row's "
    "lower right marks the patient's left"
)
_TOOTH_CORONAL_TEXT = (
    "coronal cuts tagged {tags} -- superior is up, white 'L' at the row's "
    "lower right marks the patient's left, the same as in the axial row, so "
    "for tooth {fdi} the left edge of each panel is its {near_surface} side "
    "and the right edge its {far_surface} side"
)
_TOOTH_SAGITTAL_TEXT = (
    "sagittal cuts tagged {tags}, stepping across the tooth from the "
    "patient's right to the patient's left, i.e. from its {near_surface} "
    "side to its {far_surface} side -- superior is up, white 'P' at the row's "
    "lower right marks posterior, so anterior is the left edge"
)


def _quote_tags(tags):
    """\"'a', 'b' and 'c'\" -- panel tags as they appear in caption prose."""
    quoted = [f"'{t}'" for t in tags]
    if len(quoted) == 1:
        return quoted[0]
    return ", ".join(quoted[:-1]) + f" and {quoted[-1]}"


def build_tooth_static_caption(fdi):
    """
    Static description of a tooth composite -- what the image shows, no case
    findings. Identical for every tooth bar two things that follow from the
    FDI alone: the surface names (from the tooth's quadrant and whether it is
    anterior or posterior) and the mandibular-canal sentence, which is written
    for lower teeth only because the canal is drawn on lower composites only.

    Nothing drawn on the image names a tooth SURFACE: the markers and the
    panel tags are patient directions ("L" = the patient's left, "P" =
    posterior, sagittal cuts tagged right/mid/left). Surfaces are spoken here
    instead, because which surface a patient direction lands on is per-tooth
    -- it depends on the quadrant AND on whether the tooth is anterior.
    """
    right_quadrant = (11 <= fdi <= 18 or 41 <= fdi <= 48)
    anterior       = (fdi % 10) <= 3          # FDI position 1-3: incisors, canine

    # The two surfaces at the ends of the medio-lateral axis, patient's-right
    # end first. That one pair serves both rows whose horizontal axis is X:
    # the flip puts the patient's right on the image's LEFT, so `near` is the
    # left edge of every axial and coronal panel, and it is also where the
    # sagittal row starts, since that row steps right -> left.
    #
    # A right-quadrant tooth meets its own (buccal/labial) side first, a
    # left-quadrant tooth meets it last. For an anterior tooth the same sweep
    # crosses mesial-distal instead -- an incisor's labial surface faces
    # forward, not sideways -- and mesial is the side facing the midline, so a
    # right-quadrant incisor runs distal -> mesial.
    if anterior:
        near, far = ("distal", "mesial") if right_quadrant else ("mesial", "distal")
    else:
        near, far = ("buccal", "lingual") if right_quadrant else ("lingual", "buccal")

    parts = [TOOTH_STATIC_CAPTION_INTRO.format(fdi=fdi)]
    if fdi in _LOWER_TIDS:
        parts.append(TOOTH_CANAL_CAPTION.format(fdi=fdi, colour=CANAL_COLOR_NAME))
    return " ".join(parts + [
        "Top row: " + _TOOTH_AXIAL_TEXT.format(tags=_quote_tags(_AXIAL_TAGS)) + ".",
        "Middle row: " + _TOOTH_CORONAL_TEXT.format(
            tags=_quote_tags(_CORONAL_TAGS), fdi=fdi,
            near_surface=near, far_surface=far) + ".",
        "Bottom row: " + _TOOTH_SAGITTAL_TEXT.format(
            tags=_quote_tags(_SAGITTAL_TAGS),
            near_surface=near, far_surface=far) + ".",
    ])


def build_tooth_fact_fragments(fdi, facts):
    """
    Terse fragments for whichever of the six in-scope case-level fields
    actually name this FDI. Returns [] for an empty/missing facts dict.
    """
    structured = facts.get("structured", {})

    fragments = []
    if fdi in _normalize_fdi_list(structured.get("teeth_absent")):
        fragments.append(f"Tooth {fdi} listed absent in this case's findings.")
    if fdi in _normalize_fdi_list(structured.get("crowns")):
        fragments.append(f"Tooth {fdi} crown.")
    if fdi in _normalize_fdi_list(structured.get("implants")):
        fragments.append(f"Tooth {fdi} endosseous implant.")
    for start, end in _normalize_bridge_spans(structured):
        if fdi in (start, end):
            fragments.append(f"Tooth {fdi} part of {start}-{end} fixed bridge.")
    if fdi in _normalize_fdi_list(structured.get("ian_close_teeth")):
        fragments.append(f"Tooth {fdi} close to mandibular canal.")
    return fragments


def build_tooth_caption(fdi, facts):
    """
    Static layout description plus any in-scope facts naming this tooth.
    An empty facts dict returns just the static description.
    """
    parts = [build_tooth_static_caption(fdi)]
    parts.extend(build_tooth_fact_fragments(fdi, facts))
    return " ".join(parts)


# ── FDI ↔ train-ID mapping ───────────────────────────────────────────────────

# Mask label == FDI number — use FDI directly as the mask label


# ── Case-level processing ─────────────────────────────────────────────────────

# ── Shared RAS+ loading (used by both create_tooth_detail.py and
#    create_tooth_apex_composite.py -- kept in exactly ONE place so the two
#    scripts' orientation handling can't silently drift apart) ──────────────

def load_as_ras(vol_path, mask_path):
    """
    Reorient volume and mask to RAS+ using the SAME transform.

    Why same transform:
      If computed independently, float-precision differences in the two
      affines can produce different ornt_transform results, causing the
      volume and mask to end up in different orientations (sagittal mismatch).
      Using the volume affine for both guarantees they are always aligned.

    LPS (common CBCT/DICOM convention) → RAS+:
      axis 0 L→R  (flip),  axis 1 P→A  (flip),  axis 2 S stays
    Any other input orientation is handled the same way.
    """
    import nibabel as nib
    import nibabel.orientations as nibo

    vol_nib  = nib.load(str(vol_path))
    mask_nib = nib.load(str(mask_path))

    # Derive transform from VOLUME affine only
    ornt = nibo.io_orientation(vol_nib.affine)
    ras  = nibo.axcodes2ornt(('R', 'A', 'S'))
    xfm  = nibo.ornt_transform(ornt, ras)

    print(f"  input orientation: {nibo.ornt2axcodes(ornt)} → RAS+", file=sys.stderr)

    return vol_nib.as_reoriented(xfm), mask_nib.as_reoriented(xfm)


def process_case(volume_path, mask_path, out_dir, case_id,
                 fdi_filter=None, out_w=1344, window_scale=DEFAULT_WINDOW_SCALE,
                 window_center=DEFAULT_WINDOW_CENTER,
                 window_width=DEFAULT_WINDOW_WIDTH,
                 facts_path=None):
    """
    Generate one composite image per detected tooth for a single case.
    Output: {out_dir}/{case_id}_tooth{FDI}_composite.png, plus one
    {out_dir}/{case_id}_tooth_captions.json sidecar keyed by
    "tooth_{fdi}_composite" (schema.json's images_needed key format).

    Nothing outside the volume/mask is read: the composite is nine slices of
    this case's own scan, so it no longer depends on the panoramic or the 3D
    renders having been generated first.

    `facts_path` is optional. When given, the case findings that name a
    given tooth are appended to that tooth's caption at generation time
    (see build_tooth_caption); without it every caption is the static
    layout description alone, which is still correct — just less specific.
    """
    print(f"[{case_id}] loading ...", file=sys.stderr)

    vol_nib, mask_nib = load_as_ras(volume_path, mask_path)
    # Plain get_fdata() materialises AND caches a float64 copy of each volume
    # before the downcast, so a 562³ case peaked around 6.7 GB and was
    # OOM-killed before writing a single composite. Asking for float32
    # directly, and reading the mask straight off dataobj in its stored
    # integer dtype, keeps the same arrays at roughly a third of that.
    volume   = vol_nib.get_fdata(dtype=np.float32)
    mask     = np.asanyarray(mask_nib.dataobj).astype(np.int32, copy=False)
    spacing  = float(np.mean(vol_nib.header.get_zooms()[:3]))
    print(f"  spacing: {spacing:.3f} mm  shape: {'×'.join(str(s) for s in volume.shape)}",
          file=sys.stderr)

    # Log the resolved grey-level window. Worth printing per case: it is the
    # single number that decides whether enamel and dental material come out
    # as different greys, and in percentile mode it silently differs per case.
    _lo, _hi = _resolve_window(volume, window_center, window_width, 0.5, 99.5)
    _mode = "fixed HU" if window_center is not None and window_width is not None \
            else "percentile"
    print(f"  grey window ({_mode}): [{_lo:.0f}, {_hi:.0f}] HU", file=sys.stderr)

    # Diagnostic: show which tooth train-IDs are actually present in the mask
    present_ids = sorted(v for v in np.unique(mask) if v > 10)
    print(f"  mask labels present (>10): {present_ids}", file=sys.stderr)
    expected_ids = sorted(_TEETH_IDS)
    missing_ids  = sorted(set(expected_ids) - set(present_ids))
    if missing_ids:
        print(f"  [warn] expected train IDs not in mask: {missing_ids}", file=sys.stderr)

    # Laterality FIRST, from the mask itself — every B/L and L/R marker
    # below depends on it, and this dataset contradicts its own affine.
    right_low_x = detect_right_low_x(mask)
    if right_low_x is None:
        right_low_x = True     # neither side anchorable — dataset default
        print("  [warn] laterality undetermined from mask — assuming patient "
              "RIGHT at low X", file=sys.stderr)
    else:
        print(f"  patient RIGHT is at {'LOW' if right_low_x else 'HIGH'} X "
              "(from mask)", file=sys.stderr)

    os.makedirs(out_dir, exist_ok=True)

    facts = load_case_facts(facts_path)

    all_fdis = (list(range(11,19)) + list(range(21,29)) +
                list(range(31,39)) + list(range(41,49)))
    fdis  = fdi_filter if fdi_filter else all_fdis

    # ── An excluded maxilla gets no upper composites ──────────────────────
    #
    # A composite is nine crops built around a tooth's own extent, and the
    # three "root" panels are the point of it. When the volume stops above
    # the occlusal plane there is no root to crop: S0027's tooth 16 renders
    # as a red dot at the top edge with a blank axial-root panel, and its
    # crown/caries/filling questions are unanswerable from it.
    #
    # Measured on all 622 cases -- of the 256 whose maxillary bone is out of
    # the volume but whose upper teeth are still labelled, 87.1% of reference
    # reports say nothing whatever about an upper tooth (vs 42.5% when the
    # maxilla IS imaged). The 11.7% that do describe one describe a CROWN
    # ("as far as can be visualized, prosthetic crowns are present on teeth
    # 14, 13, 12..."), which the panoramic arch read still sees --
    # dental_arch_findings_maxilla is deliberately kept for exactly that.
    #
    # This is also free: postprocess_pred.drop_excluded_maxilla already
    # discards every tooth_11..28 read for a not_included maxilla, so these
    # composites were rendered, sent to the VLM, and then thrown away. 5,440
    # calls on the training split, 41% of that group's total.
    coverage = arch_coverage(mask_label_volumes(mask, mask_nib.header.get_zooms()))
    maxilla_imaged = coverage["maxilla"]["bone"]
    if not maxilla_imaged:
        before = len(fdis)
        fdis = [f for f in fdis if f not in MAXILLA_FDIS]
        print(f"  maxilla not in the volume ({MIN_ARCH_BONE_MM3:.0f} mm^3 "
              f"threshold) — skipping {before - len(fdis)} upper composite(s)",
              file=sys.stderr)
    saved = []
    captions = {}

    for fdi in fdis:
        img = make_tooth_composite(volume, mask, tooth_tid=fdi, fdi=fdi,
                                   window_scale=window_scale,
                                   window_center=window_center,
                                   window_width=window_width,
                                   right_low_x=right_low_x,
                                   spacing_mm=spacing, out_w=out_w)
        if img is None:
            print(f"  FDI {fdi:2d}: not found — skipped", file=sys.stderr)
            continue
        out_path = os.path.join(out_dir, f"{case_id}_tooth{fdi}_composite.png")
        img.save(out_path)
        print(f"  FDI {fdi:2d} → {out_path}", file=sys.stderr)
        saved.append(out_path)

        # Caption written here rather than in a post-hoc pass, so the image
        # and the text describing it are produced by the same run.
        captions[f"tooth_{fdi}_composite"] = build_tooth_caption(fdi, facts)

    # ── Coverage sidecar ──────────────────────────────────────────────────
    #
    # The mask's verdict, written down so build_vqa_pairs.py can act on it.
    # That script has no mask -- it plans VLM calls from the images on disk --
    # and "no upper composites" alone cannot tell the two excluded cases
    # apart: 256 have upper teeth in the volume (the panoramic still shows
    # their crowns, so dental_arch_findings_maxilla is worth asking) and 98
    # have none at all (nothing to read, skip the call). One boolean each,
    # from the same arch_coverage every other stage uses.
    cov_path = os.path.join(out_dir, f"{case_id}_coverage.json")
    with open(cov_path, "w") as f:
        json.dump({arch: {k: bool(v) for k, v in vals.items()}
                   for arch, vals in coverage.items()}, f, indent=2)
    print(f"  coverage → {cov_path}", file=sys.stderr)

    n_images = len(saved)
    if captions:
        cap_path = os.path.join(out_dir, f"{case_id}_tooth_captions.json")
        with open(cap_path, "w") as f:
            json.dump(captions, f, indent=2)
        print(f"  captions → {cap_path}", file=sys.stderr)
        saved.append(cap_path)

    print(f"[{case_id}] done — {n_images} images saved.", file=sys.stderr)
    return saved


def _case_id_from_path(path):
    from pathlib import Path
    stem = Path(path).name
    for s in (".nii.gz", ".nii"):
        if stem.endswith(s):
            stem = stem[:-len(s)]
    return stem.replace("ToothFairy", "").replace("_0000", "")


def _find_volume(mask_path, volumes_dir):
    import glob
    stem = _case_id_from_path(mask_path)
    for pat in [f"*{stem}*.nii.gz", f"*{stem}*_0000.nii.gz"]:
        hits = sorted(glob.glob(os.path.join(volumes_dir, pat)))
        if hits:
            return hits[0]
    return None


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse, glob

    ap = argparse.ArgumentParser(
        description="CBCT per-tooth composite: 3x3 grid of axial / coronal / "
                    "sagittal cuts through the tooth.",
        formatter_class=argparse.RawDescriptionHelpFormatter)

    grp = ap.add_mutually_exclusive_group(required=True)
    grp.add_argument("--volume",      help="Single CBCT volume .nii.gz")
    grp.add_argument("--volumes-dir", help="Directory of volumes (batch)")

    ap.add_argument("--mask",       help="Mask .nii.gz (required with --volume)")
    ap.add_argument("--masks-dir",  help="Mask directory (required with --volumes-dir)")
    ap.add_argument("--out-dir",    required=True)
    # Accepted and ignored: the composite no longer pastes in a context panel,
    # so it reads nothing from these directories. Kept so existing pipeline
    # invocations don't fail on an unknown flag.
    ap.add_argument("--pano-dir",   default=None, help=argparse.SUPPRESS)
    ap.add_argument("--render-dir", default=None, help=argparse.SUPPRESS)
    ap.add_argument("--case-id",    default=None)
    ap.add_argument("--facts-file", default=None,
                    help="Path to this case's facts JSON (single-case mode). "
                         "Optional — without it captions carry the static "
                         "layout description only, with no case findings")
    ap.add_argument("--facts-dir",  default=None,
                    help="Directory of {case_id}.json facts files (batch "
                         "mode; matched by case_id, a missing file just "
                         "leaves that case's captions static)")
    ap.add_argument("--fdi",        type=int, nargs="+", default=None,
                    help="FDI numbers to process (default: all 32)")
    ap.add_argument("--window-scale", type=float, default=DEFAULT_WINDOW_SCALE,
                    help="Zoom of the crop window shared by all nine tiles: "
                         "1.0 = tooth + bone + pad only, larger shows more "
                         "jaw around it")
    ap.add_argument("--window-center", type=float, default=DEFAULT_WINDOW_CENTER,
                    metavar="HU",
                    help="Grey-level window CENTRE in HU (default: "
                         f"{DEFAULT_WINDOW_CENTER:g}). Lower = brighter. This "
                         "is the radiological window, not --window-scale, "
                         "which is the crop.")
    ap.add_argument("--window-width",  type=float, default=DEFAULT_WINDOW_WIDTH,
                    metavar="HU",
                    help="Grey-level window WIDTH in HU (default: "
                         f"{DEFAULT_WINDOW_WIDTH:g}). Wider = flatter, and "
                         "pushes the white point further above enamel so "
                         "dental material stays distinguishable.")
    ap.add_argument("--window-percentile", action="store_true",
                    help="Derive the grey window from this volume's own 0.5/"
                         "99.5 percentiles instead of fixed HU (pre-existing "
                         "behaviour). Brightness then varies case to case and "
                         "enamel clips to white; use only for volumes that "
                         "are not HU-calibrated.")
    ap.add_argument("--out-w",      type=int, default=1344,
                    help="Canvas width; the height follows from it (3 equal "
                         "columns, tiles at the window's own aspect)")
    ap.add_argument("--out-h",      type=int, default=None,
                    help=argparse.SUPPRESS)   # ignored: height is derived
    ap.add_argument("--limit",      type=int, default=None,
                    help="Max cases in batch mode")
    args = ap.parse_args()

    # --window-percentile is the opt-out: passing None for both bounds is what
    # _resolve_window reads as "fall back to percentiles".
    wc = None if args.window_percentile else args.window_center
    ww = None if args.window_percentile else args.window_width

    if args.volume:
        if not args.mask:
            ap.error("--mask is required with --volume")
        cid = args.case_id or _case_id_from_path(args.mask)
        process_case(args.volume, args.mask, args.out_dir, cid,
                     fdi_filter=args.fdi, out_w=args.out_w,
                     window_scale=args.window_scale,
                     window_center=wc, window_width=ww,
                     facts_path=args.facts_file)
    else:
        if not args.masks_dir:
            ap.error("--masks-dir is required with --volumes-dir")
        masks = sorted(glob.glob(os.path.join(args.masks_dir, "*.nii.gz")))
        if args.limit:
            masks = masks[:args.limit]
        print(f"Found {len(masks)} mask(s).", file=sys.stderr)
        for mp in masks:
            cid = _case_id_from_path(mp)
            vp  = _find_volume(mp, args.volumes_dir)
            if vp is None:
                print(f"  [skip] {cid}: no volume found", file=sys.stderr)
                continue
            fp = (os.path.join(args.facts_dir, f"{cid}.json")
                  if args.facts_dir else None)
            process_case(vp, mp, args.out_dir, cid,
                         fdi_filter=args.fdi, out_w=args.out_w,
                         window_scale=args.window_scale,
                         window_center=wc, window_width=ww, facts_path=fp)

    print("Done.", file=sys.stderr)